server:
  port: 9002
  shutdown: graceful

spring:
  application:
    name: product-service
  profiles:
    active: local


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource # Spring Boot 2 ?? ???? ?????? HikariCP
    hikari: # connection-timeout :  pool?? connect ?? ? ?? ??????, ?? 30??
      poolName: SpringBootJPAHikariCP # ? ?? ??
      minimum-idle: 10 # ?? ??? ? ??. ?? maximum-pool-size ? ?? ??
      maximum-pool-size: 50 # ?? ??? ? ?? ??. ?? 10?
      idle-timeout: 10000 # pool ?? ?? ??? ?? ???? ? ?? ??, minimum ? maximum ?? ???? ?? ? ???
      max-lifetime: 60000 # ??? ?? ???? (db wait_timeout ?? 2~3? ?? ????)
      connection-timeout: 10000 # ??? ??? connection? ?? ? ?? ?? ??? ????. ? ?? ? ??? ??.
      #validation-timeout: 30000 ???? ???? ??? ? ?? ??? ????. ? ??? connectionTimeout?? ??? ??. ?? ??? ?? ?? 250??.
      auto-commit: false # ??? ? auto commit ??
      data-source-properties: # JPA ??? ?? # ?? ?? ??          #(PreparedStatement : ?? ??? SQL? ???? ?? ???? ??? ?? ??
        cachePrepStmts: true # ??? ??? ??? ?? ????? ??? ???? ?? ??. ??? ??
        prepStmtCacheSize: 250 # Connection?? ??? PreparedStatement? ??? ???? ????. HikariCP??? 250 ~ 500? ??
        prepStmtCacheSqlLimit: 2048 # ??? PreparedStatement? ?? ??? ???? ????
        useServerPrepStmts: true # Server-Side PreparedStatement? ???? ????. Server-Side PreparedStatement? ??? preparedStatement? ??? ??, ? ? ?? ??? ??? ? ??.

  servlet:
    multipart: # ??? ??
      max-file-size: 10MB # ??? ?? ?? ??
      max-request-size: 50MB # ??? ?? ?? ??

  jpa:
    database: mysql # ??????
    database-platform: org.hibernate.dialect.MySQL8Dialect # ?????? ?? ??, Hinbernate ? MySQL? ?? ??? ?? 5.x innodb ??
    show-sql: true # ?????? ??? ?? ?? ??
    generate-ddl: false # DDL ?? ??
    open-in-view: false # jpa ???? ??? false? ??. true? ?? ??? ????? ???? ??? ??? ????? ????.
    hibernate:
      ddl-auto: validate # create update validate none
      #use-new-id-generator-mappings: true # JPA ??? ?? ??? ? ?? ??? ???.
    properties:
      hibernate.connection.provider_disables_autocommit: false # ID ????? ?????? ??? ?? ??
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true # ?????? sql? ?? ?? ??
      jdbc:
        order_updates: true
        batch_versioned_data: false

  main:
    allow-bean-definition-overriding: true

  cloud:
    config:
      enabled: false

logging:
  level:
    root: info
