server:
  port: 9002
  shutdown: graceful

  servlet:
    context-path: /api

spring:
  application:
    name: product-service
  profiles:
    active: local

review:
  save-rate:
    text: 3
    photo: 5
