GET http://localhost:9002/api/v1/product/category?categoryCode=cate2
Content-Type: application/json


###

###

GET http://localhost:9002/api/v1/료product/search?name=상품명
Content-Type: application/json


###

GET http://localhost:9002/api/v1/product/codeby
Content-Type: application/json


###
